version: '3.7'

services:

  supplyit-users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-stage
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@supplyit-users-db:5432/users_stage
      - DATABASE_TEST_URL=postgres://postgres:postgres@supplyit-users-db:5432/users_test
      - SECRET_KEY=my_precious
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - supplyit-users-db
      - redis

  supplyit-users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-stage
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    expose:
      - 80
    depends_on:
      - supplyit-users

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-stage
    expose:
      - 8080
    environment:
      - URL=swagger.yml
    depends_on:
      - supplyit-users

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-stage
    restart: always
    ports:
      - 80:80
    depends_on:
      - supplyit-users
      - client

  celery:
    image: users
    command: celery -A project.utils.tasks worker --loglevel=info
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - FROM_TITLE=SUPPLYIT
    depends_on:
      - supplyit-users
      - redis

  celery-monitor:
    image: users
    expose:
      - 5555
    command:  flower -A project.utils.tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - supplyit-users
      - redis

  redis:
    image: redis:5.0.7-alpine