version: '3.7'

services:

  supplyit-users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@supplyit-users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@supplyit-users-db:5432/users_test
      - SECRET_KEY=my_precious
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - supplyit-users-db

  supplyit-users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - supplyit-users
      - client

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - supplyit-users

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile
    volumes:
      - './services/swagger/swagger.yml:/usr/share/nginx/html/swagger.yml'
    ports:
      - 3008:8080
    environment:
      - URL=swagger.yml
    depends_on:
      - supplyit-users