"""empty message

Revision ID: 4242ae8dd44c
Revises: a190175a7122
Create Date: 2019-12-21 15:48:45.539330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4242ae8dd44c"
down_revision = "a190175a7122"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "user_type", sa.Enum("retail", "wholesale", name="usertype"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_type")
    # ### end Alembic commands ###
