"""empty message

Revision ID: 53a15054061e
Revises: 7491b9bfc0bc
Create Date: 2019-12-21 16:05:20.142544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "53a15054061e"
down_revision = "7491b9bfc0bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_type = postgresql.ENUM("retail", "wholesale", name="usertype")
    user_type.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "user_type", sa.Enum("retail", "wholesale", name="userType"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_type")
    user_type = postgresql.ENUM("retail", "wholesale", name="usertype")
    user_type.drop(op.get_bind())
    # ### end Alembic commands ###
