"""empty message

Revision ID: 7491b9bfc0bc
Revises: e996ac738e9b
Create Date: 2019-12-21 16:02:01.324735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7491b9bfc0bc"
down_revision = "e996ac738e9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "user_type",
            sa.Enum("retail", "wholesale", name="VARCHAR(50)"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_type")
    # ### end Alembic commands ###
