"""empty message

Revision ID: e996ac738e9b
Revises: 4242ae8dd44c
Create Date: 2019-12-21 15:59:16.411077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e996ac738e9b'
down_revision = '4242ae8dd44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.Enum('retail', 'wholesale', name='user_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
